//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayPsApit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string WorkPhone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsRealtor { get; set; }
        public string RealtorLicense { get; set; }
        public Nullable<bool> IsBroker { get; set; }
        public Nullable<bool> IsTitle { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    }
}
