//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayPsApit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiUnitDetail
    {
        public System.Guid UnitId { get; set; }
        public Nullable<System.Guid> PropertyId { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<int> SqFt { get; set; }
        public Nullable<int> BedroomCount { get; set; }
        public Nullable<int> BathroomCount { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public string SpecialFeatures { get; set; }
    }
}
