//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayPsApit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public System.Guid PropertyId { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public string Style { get; set; }
        public Nullable<int> SqFt { get; set; }
        public Nullable<int> LotSize { get; set; }
        public Nullable<bool> IsMultiUnit { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<decimal> HoaFees { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public Nullable<bool> OccupantId { get; set; }
        public string SpecialFeatures { get; set; }
        public string RepairsNeeded { get; set; }
        public string Upgrades { get; set; }
        public Nullable<bool> IsListed { get; set; }
        public Nullable<System.DateTime> ListingDate { get; set; }
        public Nullable<bool> HasOtherOffers { get; set; }
        public Nullable<decimal> OfferAmount { get; set; }
        public string Realtor { get; set; }
        public string RealtorPhone { get; set; }
        public string ReasonForSelling { get; set; }
        public string TimeFrame { get; set; }
        public string NoSellContingency { get; set; }
        public Nullable<decimal> MortgageAmount { get; set; }
        public Nullable<bool> HasLiens { get; set; }
        public Nullable<bool> HasMultipleMortgages { get; set; }
        public Nullable<bool> IsPaymentCurrent { get; set; }
        public Nullable<bool> MonthsBehind { get; set; }
        public Nullable<decimal> AmountBehind { get; set; }
        public Nullable<decimal> BackTaxes { get; set; }
        public Nullable<decimal> OtherLeinAmount { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> FirstInterestRate { get; set; }
        public Nullable<decimal> SecondInterestRate { get; set; }
        public Nullable<bool> IsFixedRate { get; set; }
        public Nullable<decimal> PaymentPenalty { get; set; }
        public string MortgageCompany1 { get; set; }
        public string MortgageCompany2 { get; set; }
        public Nullable<decimal> AskingPrice { get; set; }
        public Nullable<bool> IsFlexible { get; set; }
        public string HowPriceDerived { get; set; }
        public Nullable<decimal> BestPriceCashFastClose { get; set; }
        public Nullable<decimal> AbsoluteBottomPrice { get; set; }
        public Nullable<bool> WillSubjectTo { get; set; }
        public Nullable<bool> CanAcceptQuickly { get; set; }
        public Nullable<System.Guid> EvaluatorId { get; set; }
        public Nullable<decimal> ARV { get; set; }
        public Nullable<decimal> AsIsValue { get; set; }
        public Nullable<decimal> RepairCost { get; set; }
        public Nullable<bool> LikelyPurchase { get; set; }
        public string ExitStrategy { get; set; }
        public Nullable<decimal> Offer1 { get; set; }
        public Nullable<decimal> Offer2 { get; set; }
    }
}
